### ISSUE TITLE
[MentionChannels] - Broken again after recent update

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [Echological/MentionChannels-BD#7]
@Echological seems a recent update has broken it again.
getting errors in console & debug log.

[discord.com-1643704496575.log](https://github.com/Echological/MentionChannels-BD/files/7976966/discord.com-1643704496575.log)
[debug.log](https://github.com/Echological/MentionChannels-BD/files/7976973/debug.log)
![Screen Shot 2022-02-01 at 7 35 06 pm](https://user-images.githubusercontent.com/2242880/151936651-8f4bbd90-8758-41a9-ab4c-7f8abdb2ea21.jpg)

```
Stable 112818 (e65900e)
BetterDiscord 1.5.0
Host 0.0.264 OS X 10.15.7 (20.6.0)
```

**Comment by Echological** [comment]
fixed
